# docker-compose.yml

services:
  redis-service:
    image: "redis:latest"
    networks:
      - backend-network
    volumes:
      - "redis-volume:/data"
  web-service:
    build: ./web
    ports:
      - "80:5000"
    environment:
      REDIS_URL: "redis://redis-service:6379"
    networks:
      - backend-network
    depends_on:
      - redis-service
    # This command takes precedence over Dockerfile’s default CMD 
    # To show difference it runs server on port 8000 instead of 5000
    command: "gunicorn page-tracker.app:app --bind 0.0.0.0:8000"

networks:
    backend-network:

volumes:
  redis-volume: