name: Continuous Integration

on:
  pull_request: 
    branches: 
      - master
  push: 
    branches: 
      - master

jobs:
  build:
    name: build DOcker image and run E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from Github
        uses: actions/checkout@v3
      - name: run E2E tests
        run: >
          docker compose --profile testing up
          --build 
          --exit-code-from test-service
      - name: login to Docker hub
        uses: docker/login-actions@v2
        if: ${{ github.event == "push" }}
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    
      
